config/routes.rb
Rails.application.routes.draw do  
  devise_for :users, only: :omniauth_callbacks, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  scope '(:locale)', locale: /en|ru/ do
    
    devise_for :users, skip: :omniauth_callbacks
    resources :tags, only: [:show]
    resources :reviews do
      resources :likes
      resources :user_ratings
  
    end
    resources :users, only: [:index, :show, :edit, :update]


    root to: 'main_page#index'
    get "search", to: "search#search"
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :likes, dependent: :destroy
  has_many :user_rating, dependent: :destroy
  has_many :reviews
  
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      
      # If you are using confirmable and the provider(s) you use validate emails, 
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def countUserLikes
    @reviews = self.reviews
    sum = 0
    @reviews.each do |review|
      sum += review.likes.count
    end
    return sum.to_s
  end

  
  def nick
    self.email[0..self.email.index('@')-1]
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:facebook, :google_oauth2]
         


  
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]
  skip_before_action :verify_authenticity_token, only: :facebook

  def facebook
   
   @user = User.from_omniauth(request.env["omniauth.auth"])
 
   if @user.persisted?
     flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Facebook"
     sign_in_and_redirect @user, :event => :authentication
   else
     session["devise.facebook_data"] = request.env["omniauth.auth"].except(:extra) # Removing extra as it can overflow some session stores
     redirect_to new_user_registration_url
   end
 end
 
 def google_oauth2
  @user = User.from_omniauth(request.env["omniauth.auth"])
  if @user.persisted?
    flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Google"
    sign_in_and_redirect @user, :event => :authentication
  else
    session["devise.google_data"] = request.env["omniauth.auth"]
    redirect_to new_user_registration_url
  end
 end

 def failure
   redirect_to root_path
 end
  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: %i[index, show]
  
  def index
    if current_user.admin
      @users = User.all
    else
      redirect_to root_path  
    end
  end
  
  def show
    
    @categories = Category.all
    @user = User.find(params[:id])
    
    @reviews = @user.reviews
    

    @showUserInfo = @user.nick + ' (' + t('profile.likesCount') + @user.countUserLikes + ')'
  end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<h2>Users list: </h2>
<ul class="list-group">
<% @users.each do |user| %>
  <% if user.admin %>
  <li class="list-group-item list-group-item-danger"><%= link_to user.email, user %></li>
  <% else %>
  <li class="list-group-item"><%= link_to user.email, user %></li>
  <% end %> 
<% end %>
</ul>

app/views/users/show.html.erb
<% if user_signed_in? && current_user.email == @user.email %>
<h3><%=t('profile.yourProfile')%></h3>
<%= link_to t('profile.newReview'), new_review_path, class:"w-100 btn btn-lg btn-success"%><p></p>
<%end%>
<% if user_signed_in? && current_user.admin %>
<%= link_to t('profile.adminPanel'), users_path, class:"w-100 btn btn-lg btn-danger"%><p></p>
<%end%>

<h2><b><%= t('profile.whoisReviews') +' '+ @showUserInfo %></b></h2>

<% if params[:category]%>
<%= link_to t("profile.resetFiltres") %>
<%end%>

<table class="table">
  <thead>
  
    <tr>
    
      <th scope="col"><h5> #  </h5></th>
      <th scope="col"><h5>
      
      
      
      <% @categories.each do |category|%>
      <option><%= link_to category.name, :category=>category.id %></option>
      <% end %>
      
      
      </h5></th>
      <th scope="col"><h5><%= t('profile.name') %></h5></th>
      <th scope="col"><h5><%=t('homepage.avg')%></h5></th>
      <th scope="col"><h5><%= t('profile.created_at') %></h5></th>
      <th scope="col"><h5><%= t('profile.edited_at') %></h5></th>
      <th scope="col"><h5><%=t('profile.options')%></h5></th>
    
    </tr>
  </thead>
  <tbody>
  <% if params[:category].present? %>
  <% @reviews = @reviews.where(category_id: params[:category])%>
  <% end %>
  <% @reviews.reverse.each_with_index do |review, index| %>
    <tr>
      <th scope="row"><h5><%= index+1 %></h5></th>
      <td><h5><%= review.category.name%></h5></td>
      <td><h5><%= review.name%></h5></td>
      <td><h5><%= review.user_rating.average('score').to_d %></h5></td>
      <td><h5><%= review.created_at%></h5></td>
      <td><h5><%= review.updated_at%></h5></td>
      <td><%= link_to t('profile.show'), review, class:"btn btn-success"%> 
      <% if user_signed_in? && (current_user.admin || current_user == review.user) %>
      <%= link_to t('profile.edit'), edit_review_path(review), class:"btn btn-warning" %>
      <%= link_to t('profile.destroy'), review, :method => :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %>
      </td>
      <% end %>
    </tr>
    <% end %>
    
  </tbody>
</table>