config/routes.rb
Rails.application.routes.draw do  
  devise_for :users, only: :omniauth_callbacks, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  scope '(:locale)', locale: /en|ru/ do
    
    devise_for :users, skip: :omniauth_callbacks
    resources :tags, only: [:show]
    resources :reviews do
      resources :likes
      resources :user_ratings
  
    end
    resources :users, only: [:index, :show, :edit, :update]


    root to: 'main_page#index'
    get "search", to: "search#search"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base

  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
 has_many :reviews
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :review
  belongs_to :user
end

app/models/review.rb
require 'elasticsearch/model'
class Review < ApplicationRecord
 include Elasticsearch::Model
 include Elasticsearch::Model::Callbacks
 has_rich_text :content

 belongs_to :user
 belongs_to :category
 has_many :likes, dependent: :destroy
 has_many :user_rating, dependent: :destroy
 has_many :taggings
 has_many :tags, through: :taggings

 def all_tags
  self.tags.map(&:name).join(', ')
 end

 def all_tags=(names)
  self.tags = names.split(', ').map do |name|
   Tag.where(name: name.strip).first_or_create!
  end
 end
 
 validates :name, :all_tags, presence: true
 validates :content, length: { minimum: 100 }, presence: true

 


end

app/models/tag.rb
class Tag < ApplicationRecord
 has_many :taggings
 has_many :reviews, through: :taggings
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :review
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  has_many :likes, dependent: :destroy
  has_many :user_rating, dependent: :destroy
  has_many :reviews
  
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      
      # If you are using confirmable and the provider(s) you use validate emails, 
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def countUserLikes
    @reviews = self.reviews
    sum = 0
    @reviews.each do |review|
      sum += review.likes.count
    end
    return sum.to_s
  end

  
  def nick
    self.email[0..self.email.index('@')-1]
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:facebook, :google_oauth2]
         


  
end

app/models/user_rating.rb
class UserRating < ApplicationRecord
 belongs_to :review
 belongs_to :user
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
 before_action :find_review, :userLikeOnReview 
 
 def create
  @review.likes.create(user_id: current_user.id)
  redirect_to review_path(@review)
 end  
  

 def destroy
  @like.destroy_all
  redirect_to review_path(@review)
 end 


  private  
  
  def userLikeOnReview
   if user_signed_in?
    @like = Like.where(user_id: current_user.id, review_id: params[:review_id])
   end
  end

  def find_review
    @review = Review.find(params[:review_id])
  end
end

app/controllers/main_page_controller.rb
class MainPageController < ApplicationController
  def index
    @categories = Category.all
    @reviewsRated = Review.all.sort_by{|h| h.user_rating.average('score').to_d}.last(3).reverse
    @reviewsLast = Review.last(3).reverse
    @tags = Tag.all.sort_by{|h| h.taggings.count}.last(6)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: %i[new edit create update destroy]
  before_action :userLikeOnReview, :userRatingOnReview, only: %i[show]
  before_action :userRatingOnReview, only: %i[show index]

  def index
    @reviews = Review.all.paginate(page: params[:page], per_page: 4).order("created_at DESC")
    
  end

  def show
    
    @showAuthorInfo = @review.user.nick + ' ('+ t('profile.likesCount') + @review.user.countUserLikes + ')'
  end

  def new
    @users = User.all
    @categories = Category.all
    @review = Review.new
    
  end

  def edit
    if set_review.user.id == current_user.id || current_user.admin
      @categories = Category.all
      @users = User.all
    else
      redirect_to root_path
    end
  end

  def create
    @categories = Category.all
    @review = Review.new(review_params)
    @review.update(body: @review.content)

    respond_to do |format|
      if @review.save
        
        format.html { redirect_to @review, notice: t('review.created') }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to @review.user, notice: t('review.destroyed') }
      format.json { head :no_content }
    end
  end

  def update
    @categories = Category.all
    respond_to do |format|
      if @review.update(review_params)
      @review.update(body: @review.content)
          format.html { redirect_to @review, notice: t('review.edited')}
          format.json { render :show, status: :ok, location: @review }
        
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end
  

  

  private

  def userLikeOnReview
    if user_signed_in?
    @like = Like.where(user_id: current_user.id, review_id: params[:id])
    end
  end

  def userRatingOnReview
    if user_signed_in?
    @rating = UserRating.where(user_id: current_user.id, review_id: params[:id])
    end
  end


    def set_review
      @review = Review.find(params[:id])
    end

 
    def review_params
    if current_user.admin   
      params.require(:review).permit(:category_id, :name, :content, :rating, :all_tags, :user_id)
    else
      params.require(:review).permit(:category_id, :name, :content, :rating, :all_tags).merge(user_id: current_user.id)
    end  
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
 def search
  if params[:q].nil?
    @reviews = []
  else
    @reviews = Review.search params[:q]
  end
 end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
 def show
  @tag = Tag.find_by(name: params[:id])
  @reviews = @tag.reviews
 end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: %i[index, show]
  
  def index
    if current_user.admin
      @users = User.all
    else
      redirect_to root_path  
    end
  end
  
  def show
    
    @categories = Category.all
    @user = User.find(params[:id])
    
    @reviews = @user.reviews
    

    @showUserInfo = @user.nick + ' (' + t('profile.likesCount') + @user.countUserLikes + ')'
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/main_page_helper.rb
module MainPageHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/user_ratings_helper.rb
module UserRatingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/main_page/index.html.erb
<main>

  <div class="container " id="featured-3">
    <h2 class="pb-2 border-bottom"> <%= t('homepage.mostLiked') %> </h2>
    <div class="row g-4 py-5 row-cols-1 row-cols-lg-3">
    <% @reviewsRated.each do |review| %>
      <div class="col d-flex align-items-start">
        
        <div>
          <h2><%= t('homepage.reviewOn') + ' "' + review.name + '"' %>
          <%= raw review.tags.map(&:name).map{|t| link_to t, tag_path(t), class: "btn btn-primary btn-sm"}.join(' ')%>
          </h2>
          <p><%= t('homepage.avg') %>: <%= review.user_rating.average('score').to_d %></p>
          
          <p><% if review.content.to_plain_text.length < 500 %> 
          <%= review.content %>
          <%else%>
          <%= review.content.to_plain_text[0..500] + '...' %>
          <%end%></p>
          
          <%= link_to t('homepage.readMore'), review, class:"btn btn-primary" %> 
          
        </div>
      </div>
    <% end%>
      
    </div>
  </div>

  <div class="b-example-divider"></div>

  <div class="container " id="hanging-icons">
    <h2 class="pb-2 border-bottom"><%= t('homepage.lastAdded') %></h2>
    <div class="row g-4 py-5 row-cols-1 row-cols-lg-3">
      <% @reviewsLast.each do |review| %>
      <div class="col d-flex align-items-start">
      
        <div>
          <h2><%= t('homepage.reviewOn') + ' "' + review.name + '"' %></h2>
          <%= raw review.tags.map(&:name).map{|t| link_to t, tag_path(t), class: "btn btn-primary btn-sm"}.join(' ')%>
          
          <p><%= t('homepage.avg') %>: <%= review.user_rating.average('score').to_d %></p>
          
          <p><% if review.content.to_plain_text.length < 500 %> 
          <%= review.content %>
          <%else%>
          <%= review.content.to_plain_text[0..500] + '...' %>
          <%end%></p>
          
          <%= link_to t('homepage.readMore'), review, class:"btn btn-primary" %>
          
        </div>
      </div>
      <% end%>
    </div>
  </div>

  

  <div class="b-example-divider"></div>

  <div class="container " id="icon-grid">
    <h2 class="pb-2 border-bottom"><%= t('homepage.tags') %></h2>

    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-6 g-6 py-1">
<% @tags.reverse.each do |tag|%>
      <div class="col d-flex align-items-start">
        <svg class="bi text-muted flex-shrink-0 me-3" width="1.75em" height="1.75em"><use xlink:href="#bootstrap"/></svg>
        <div>
          <h4 class="fw-bold mb-0"><%= link_to tag.name, tag_path(tag.name), class: "btn btn-primary btn-lg"%></h4>
          
        </div>
      </div>
<%end%>
      
    </div>
  </div>
</main>

app/views/reviews/_form.html.erb
<%= form_with(model: review) do |form| %>
  <% if review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(review.errors.count, t('review.errors.error')) + ' '+ t('review.errors.title') %></h2>

      <ul>
        <% review.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>



<div class="row g-3 align-items-center">
  <div class="col-auto">
    <label for="chooseCategory" class="col-form-label"><%= t('review.chooseCategory')%></label>
  </div>
  <div class="col-auto">
  <select class='form-control' name='review[category_id]'>
  <% @categories.each do |category|%>
<option value="<%= category.id %>"<%if @review.category_id == category.id%>selected=selected<%end%>><%= category.name %></option>
<%end%>
</select>
  </div>
</div>
<br />
<div class="row g-3 align-items-center">
  <div class="col-auto">
    <label class="col-form-label"><%= t('review.name')%> </label>
  </div>
  <div class="col-auto">
  <%= form.text_field :name,  class:"form-control"%>
    
  </div>
  
</div>


  <div class="field">
    <label class="col-form-label"><%= t('review.content')%> </label>
    <%= form.rich_text_area :content %>
  </div>
<p></p>
<div class="row g-3 align-items-center">
  <div class="col-auto">
    <label class="col-form-label"><%= t('review.myRating')%></label>
  </div>
  <div class="col-auto">
  <%= form.select :rating, ['1' ,'2','3','4','5','6','7','8','9','10'], {}, class:"form-control" %>
    
  </div>

    <div class="field">
    <label class="col-form-label"><%= t('homepage.tags')%> </label>
    <%= form.text_field :all_tags, class: "form-control" %>
  </div>
  
<% if current_user.admin %>
  

<div class="field">
<%= t('review.chooseUser') %>
<select class='form-control' name='review[user_id]'>
  <% @users.each do |user|%>
<option value="<%= user.id %>"

<%if @review.user_id && (@review.user_id == user.id)%>
selected = selected
<% elsif user.id == current_user.id %>
selected = selected
<%end%>
>
<%= user.email %>
</option>

<%end%>
</select>
</div>
  
<%end%>
  
    <%= form.submit t('review.create'), class:"w-100 btn btn-lg btn-success" %>
  
<% end %>

app/views/reviews/edit.html.erb
<h1><%= t('review.edit')%></h1>

<%= render 'form', review: @review %>

app/views/reviews/index.html.erb
<%@reviews.each do |review|%>
<div class="card">
  <div class="card-header">
    <%= t('review.author')%>
<%= link_to review.user.nick + ' ('+ t('profile.likesCount') + review.user.countUserLikes + ')', review.user %> 
  </div>
  <div class="card-body">
    <h5 class="card-title"><%= t('homepage.reviewOn')+ ' "'+ review.name+'"'%> 
    <%= raw review.tags.map(&:name).map{|t| link_to t, tag_path(t), class: "btn btn-primary btn-sm"}.join(' ')%>
    </h5>
    <p class="card-text">
    
    <% if review.content.to_plain_text.length < 1000 %> 
    <%= review.content %>
    <%else%>
    <%= review.content.to_plain_text[0..1000] + '...' %>
    <%end%>
    </p>
    <%= link_to t('homepage.readMore'), review, class:"btn btn-primary" %>
    <p></p>
    <%= t('homepage.avg') %>: <%= review.user_rating.average('score').to_d %>
  </div>
  <div class="card-footer text-muted">
    <%= t('profile.created_at') + ' '+ review.created_at.to_s%> 
    <% if review.created_at.to_s != review.updated_at.to_s %>
   | <%= t('profile.edited_at') + ' '+ review.updated_at.to_s%>
    <% end %>
    
  </div>
</div>
<p></p>
<%end%>

<div class="apple_pagination">
  <div class="page_info">
    <%= page_entries_info @reviews %>
  </div>
  <%= will_paginate @reviews, :container => false %>
</div>

app/views/reviews/new.html.erb
<h1><%= t('review.new')%></h1>

<%= render 'form', review: @review %>

app/views/reviews/show.html.erb
<div class="card">
  <div class="card-header">
  
    <%= t('review.author')%> <%= link_to @showAuthorInfo, @review.user %> 
    | <%= t('homepage.avg') %>: <%= @review.user_rating.average('score').to_d %>
    
  </div>
  <div class="card-body">
    <h5 class="card-title">
    <p><%= t('review.group')%><%= @review.category.name %></p>
    <p><%= t('review.name') + ' "'+ @review.name + '"' %></p>
    <p><%= t('review.content')%></p>
    </h5>
    <p>
    <div class="h-100 p-3 bg-light border rounded-3">
    <%= @review.content %>
    </div>
    <h5 class="card-title">
    </p>
    <%= t('review.authorRating')%><%= @review.rating %>
    </h5>
    <%= raw @review.tags.map(&:name).map{|t| link_to t, tag_path(t), class: "btn btn-primary btn-sm"}.join(' ')%>
  </div>
  <div class="card-footer text-muted">
  
    <%= t('profile.created_at') + ' '+ @review.created_at.to_s%> 
    <% if @review.created_at.to_s != @review.updated_at.to_s %>
   | <%= t('profile.edited_at') + ' '+ @review.updated_at.to_s%>
    <% end %>
  </div>
    <% if user_signed_in? %>
    <% if current_user.admin || current_user.id == @review.user.id %>
    <div class="card-footer text-muted">
      <%= link_to t('profile.edit'), edit_review_path(@review), class:"btn btn-warning" %>
      <%= link_to t('profile.destroy'), @review, :method => :delete, data: { confirm: t('review.confirm') }, class:"btn btn-danger" %> 
    </div>
    <% end %>
    
    <div class="card-footer text-muted text-center">
      <% if !@rating.exists? %>
      

      
        <%= link_to 'Rate 1', review_user_ratings_path(@review, :score => 1), method: :post, class:"btn btn-info" %>
        <%= link_to 'Rate 2', review_user_ratings_path(@review, :score => 2), method: :post,  class: "btn btn-info" %>
        <%= link_to 'Rate 3', review_user_ratings_path(@review, :score => 3), method: :post,  class: "btn btn-info" %>
        <%= link_to 'Rate 4', review_user_ratings_path(@review, :score => 4), method: :post,  class: "btn btn-info" %>
        <%= link_to 'Rate 5', review_user_ratings_path(@review, :score => 5), method: :post,  class: "btn btn-info" %>
      
      <%else%>
        <%= link_to 'Unrate', review_user_rating_path(@review), method: :delete, class: "btn btn-info" %>
      <%end%>
      </div>
      <div class="card-footer text-muted text-center">
      <% if @like.exists? %>
        <%= button_to t('review.unlike'), review_like_path(@review), method: :delete, class: "btn btn-info" %>
      <% else %>
        <%= button_to t('review.like'), review_likes_path(@review), method: :post, class: "btn btn-info" %>
      <%end%>
      </div>
    <%end%>
  </div>
</div>

app/views/search/search.html.erb
<h1><%=t('review.search')%></h1>
<div class="row g-3 align-items-center">
 <div class="col-auto">
  <%= form_for search_path, method: :get do |f| %>
  
   <div class="col-auto">
    <%= text_field_tag :q, params[:q], placeholder: t('navbar.typesearch'), class: "form" %> <%= submit_tag t('navbar.search'), name: nil, class:"btn btn-primary" %>
<p></p>
<% end %>
</div>
</div>


<p></p>
<%@reviews.each do |review|%>
<div class="card">
  <div class="card-header">
    <%= t('review.author')%>
<%= link_to Review.find(review._id).user.nick + ' ('+ t('profile.likesCount') + Review.find(review._id).user.countUserLikes + ')', Review.find(review._id).user %> 
  </div>
  <div class="card-body">
    <h5 class="card-title"><%= t('homepage.reviewOn')+ ' "'+ review.name+'"'%> 
    <%= raw Review.find(review._id).tags.map(&:name).map{|t| link_to t, tag_path(t), class: "btn btn-primary btn-sm"}.join(' ')%>
    </h5>
    <p class="card-text">
    
    <% if Review.find(review._id).content.to_plain_text.length < 1000 %> 
    <%= Review.find(review._id).content %>
    <%else%>
    <%= Review.find(review._id).content.to_plain_text[0..1000] + '...' %>
    <%end%>
    </p>
    <%= link_to t('homepage.readMore'), review_path(review._id), class:"btn btn-primary" %>
    <p></p>
    <%= t('homepage.avg') %>: <%= Review.find(review._id).user_rating.average('score').to_d %>
  </div>
  <div class="card-footer text-muted">
    <%= t('profile.created_at') + ' '+ Review.find(review._id).created_at.to_s%> 
    <% if Review.find(review._id).created_at.to_s != Review.find(review._id).updated_at.to_s %>
   | <%= t('profile.edited_at') + ' '+ Review.find(review._id).updated_at.to_s%>
    <% end %>
    
  </div>
</div>
<p></p>
<%end%>