config/routes.rb
Rails.application.routes.draw do  
  devise_for :users, only: :omniauth_callbacks, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  scope '(:locale)', locale: /en|ru/ do
    
    devise_for :users, skip: :omniauth_callbacks
    resources :tags, only: [:show]
    resources :reviews do
      resources :likes
      resources :user_ratings
  
    end
    resources :users, only: [:index, :show, :edit, :update]


    root to: 'main_page#index'
    get "search", to: "search#search"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base

  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
 has_many :reviews
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :review
  belongs_to :user
end

app/models/review.rb
require 'elasticsearch/model'
class Review < ApplicationRecord
 include Elasticsearch::Model
 include Elasticsearch::Model::Callbacks
 has_rich_text :content

 belongs_to :user
 belongs_to :category
 has_many :likes, dependent: :destroy
 has_many :user_rating, dependent: :destroy
 has_many :taggings
 has_many :tags, through: :taggings

 def all_tags
  self.tags.map(&:name).join(', ')
 end

 def all_tags=(names)
  self.tags = names.split(', ').map do |name|
   Tag.where(name: name.strip).first_or_create!
  end
 end
 
 validates :name, :all_tags, presence: true
 validates :content, length: { minimum: 100 }, presence: true

 


end

app/models/tag.rb
class Tag < ApplicationRecord
 has_many :taggings
 has_many :reviews, through: :taggings
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :review
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  has_many :likes, dependent: :destroy
  has_many :user_rating, dependent: :destroy
  has_many :reviews
  
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      
      # If you are using confirmable and the provider(s) you use validate emails, 
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def countUserLikes
    @reviews = self.reviews
    sum = 0
    @reviews.each do |review|
      sum += review.likes.count
    end
    return sum.to_s
  end

  
  def nick
    self.email[0..self.email.index('@')-1]
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:facebook, :google_oauth2]
         


  
end

app/models/user_rating.rb
class UserRating < ApplicationRecord
 belongs_to :review
 belongs_to :user
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
 before_action :find_review, :userLikeOnReview 
 
 def create
  @review.likes.create(user_id: current_user.id)
  redirect_to review_path(@review)
 end  
  

 def destroy
  @like.destroy_all
  redirect_to review_path(@review)
 end 


  private  
  
  def userLikeOnReview
   if user_signed_in?
    @like = Like.where(user_id: current_user.id, review_id: params[:review_id])
   end
  end

  def find_review
    @review = Review.find(params[:review_id])
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
 def search
  if params[:q].nil?
    @reviews = []
  else
    @reviews = Review.search params[:q]
  end
 end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
 def show
  @tag = Tag.find_by(name: params[:id])
  @reviews = @tag.reviews
 end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: %i[index, show]
  
  def index
    if current_user.admin
      @users = User.all
    else
      redirect_to root_path  
    end
  end
  
  def show
    
    @categories = Category.all
    @user = User.find(params[:id])
    
    @reviews = @user.reviews
    

    @showUserInfo = @user.nick + ' (' + t('profile.likesCount') + @user.countUserLikes + ')'
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/main_page_helper.rb
module MainPageHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/user_ratings_helper.rb
module UserRatingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HTWT</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  
  <body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <label class="navbar-brand" ><b>How to waste time</b></label>
    
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
        <%= link_to t('navbar.home'), root_path, {class: "nav-link active", 'aria-current':"page"} %>
          
        </li>
        
        <li class="nav-item ">
          <%= link_to t('navbar.all'), reviews_path, {class: "nav-link active", 'aria-current':"page"} %></a>
            
            
            
          
        </li>         
      </ul>
      
      <div class="btn-group me-2">
        <button type="button" class="btn btn-outline-danger dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
        <%= t('navbar.language') %>
        </button>
        <ul class="dropdown-menu">
                       
        <li> <%= link_to t('navbar.enus'), {locale: :en}, class: "dropdown-item" %></li>
        <li> <%= link_to t('navbar.ruru'), {locale: :ru}, class: "dropdown-item" %></li>
        
        </ul>
      </div>
      <br>
      
      <div class="btn-group" role="group" aria-label="Basic radio toggle button group">
        <input type="radio" class="btn-check" name="btnradio" id="btnradio1" autocomplete="off" checked>
        <label class="btn btn-outline-primary" for="btnradio1"><%= t('navbar.ltheme') %></label>

        <input type="radio" class="btn-check" name="btnradio" id="btnradio2" autocomplete="off">
        <label class="btn btn-outline-primary" for="btnradio2"><%= t('navbar.dtheme') %></label>

      </div>
      
      
        
          <% if user_signed_in? %>
      
      
          <%= link_to t('navbar.myProfile'), user_path(current_user), {class: "nav-link active", 'aria-current':"page"} %>
          <%= link_to t('navbar.logOut'), destroy_user_session_path, {:method => :delete, class: "nav-link active", 'aria-current':"page"} %>
          
      
          
          <% else %>
        
          <%= link_to t('navbar.logIn'), new_user_session_path, {class: "nav-link active", 'aria-current':"page"} %>
          <%= t('navbar.or') %>
          <%= link_to t('navbar.signUp'), new_user_registration_path, {class: "nav-link active", 'aria-current':"page"} %>
        
          <% end %>
              
      
        
        
        
      </span>
      <form class="d-flex">
      
        <%= link_to t('navbar.search'),search_path, class: "btn btn-outline-success"%>
        
      </form>
    </div>
  </div>
</nav>
<div class='container'>

<% if alert %>
<br>
<p class="alert alert-danger" role="alert"><%= alert %></p>
<% end %>
<% if notice %>
<br>
<p class="alert alert-primary" role="alert"><%= notice %></p>
<% end %>
<br>

    <%= yield %>
    </div>
  </body>
</html>